### ISSUE TITLE
prettier conflicts with no-unexpected-multiline

### ISSUE THREAD

**Issue by sudo-suhas** [prettier/eslint-config-prettier#32]
This scenario is relevant when a shareable config like `airbnb-base` is combined with `prettier`. If the rule `no-unexpected-multiline` is enabled, it ends up resulting in a error which can only be resolved by switching off the rule.

**.eslintrc.yml**

```yml
extends: prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 8
  sourceType: script
rules:
  no-undef: off
  no-unused-vars: off
  no-unexpected-multiline: error
  prettier/prettier:
    - error
    -
      trailingComma: none
      singleQuote: true
      printWidth: 80
      tabWidth: 4

```

**code snippet**

```js
const value =
    Array.isArray(param) && spread
        ? getInstance()
              [methodName](...param)
              .toJSON()
        : getInstance()
              [methodName](param)
              .toJSON();
```

**Eslint output:**

```
  4:15  error  Unexpected newline between object and [ of property access  no-unexpected-multiline
  7:15  error  Unexpected newline between object and [ of property access  no-unexpected-multiline
```

If I fix the errors:
```
  3:24  error  Insert `⏎··············`  prettier/prettier
  5:24  error  Insert `⏎··············`  prettier/prettier
```
